services:
    _defaults:
        autowire: true
        autoconfigure: true

    Auth0\JWTAuthBundle\Security\Auth0Service:
        arguments:
            $tokenVerifiers: !tagged_iterator jwt_auth.module.definition
            $logger: '@?logger'

    Auth0\JWTAuthBundle\Security\Guard\JwtGuardAuthenticator: ~
    Auth0\JWTAuthBundle\Security\User\JwtUserProvider: ~

    jwt_auth.auth0_service: '@Auth0\JWTAuthBundle\Security\Auth0Service'
    jwt_auth.security.guard.jwt_guard_authenticator: '@Auth0\JWTAuthBundle\Security\Guard\JwtGuardAuthenticator'
    jwt_auth.security.user.jwt_user_provider: '@Auth0\JWTAuthBundle\Security\User\JwtUserProvider'
